# Generated by Django 3.2.6 on 2021-08-23 01:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("011", "011"),
                            ("016", "016"),
                            ("017", "017"),
                            ("018", "018"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "destiny",
                    models.CharField(
                        choices=[
                            ("011", "011"),
                            ("016", "016"),
                            ("017", "017"),
                            ("018", "018"),
                        ],
                        max_length=3,
                    ),
                ),
                ("talk_more_tariff", models.FloatField()),
                ("default_tariff", models.FloatField()),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("talk_more_low", "talk more low"),
                            ("talk_more_medium", "talk more medium"),
                            ("talk_more_high", "talk more high"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("minutes", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
        ),
    ]
